### ISSUE TITLE
Bot crashes on losing connection to Twitch PubSub

### ISSUE THREAD

**Issue by Supinic** [caglapickaxe/charlestonbieber#8]
The bot seems to crash completely whenever the connection to PubSub is lost.
An expected would probably be to keep attempting to reconnect instead.

**Error stack**
```
Error: getaddrinfo EAI_AGAIN pubsub-edge.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
Emitted 'error' event on WebSocket instance at:
    at ClientRequest.<anonymous> 
```

**Comment by caglapickaxe** [comment]
This is also an issue in Mixer client. I don't know if it will crash the bot, but the error should be handled.
